config/routes.rb
Rails.application.routes.draw do
  root 'sessions#main'
  resources :users
  resources :tweets
  resources :likes

  post 'sessions/login'
  post 'sessions/signin'
  get  'sessions/signin_view'
  post 'sessions/logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  
  validates :user_id, presence: true
  validates :tweet_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  
  validates :user_id, presence: true
  
  def like(user)
    likes.create(user_id: user.id)
  end
  
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
  
  def liked?(user)
    like_users.include?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_tweets, through: :likes , source: :tweet
  
  validates :uid, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true
  
  attr_accessor :password, :password_confirmation

  def password=(val)
    if val.present?
      self.pass = BCrypt::Password.create(val)
    end
    @password = val
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  private
    def current_user
      if session[:login_uid]
        User.find_by(uid: session[:login_uid])
      end
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    user = User.find_by(uid: session[:login_uid])
    user.like_tweets << tweet
    redirect_to root_path
  end
  def destroy
    tweet = Tweet.find(params[:id])
    user = User.find_by(uid: session[:login_uid])
    tweet.likes.find_by(user_id: user.id).destroy
    redirect_to root_path
  end
  
  def create
    tweet = Tweet.find(params[:tweet_id])
    unless tweet.liked?(current_user)
    tweet.like(current_user)
    end
    redirect_to root_path
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
   if tweet.liked?(current_user)
    tweet.unlike(current_user)
    end
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def main
    if current_user
      redirect_to '/tweets'
    else
      render 'login'
    end
  end
  
  def login
    user = User.find_by(uid: params[:uid])
    if user && BCrypt::Password.new(user.pass) == params[:pass]
      session[:login_uid] = params[:uid]
      redirect_to root_path
    else
      render 'error'
    end
  end
  
  def signin
    @user = User.new(
    uid: params[:uid],
    password: params[:password],
    password_confirmation: params[:password_confirmation])
    if @user.save
      session[:login_uid] = params[:uid] 
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def signin_view
    render 'signin'
  end
  
  def logout
    session.delete(:login_uid)     
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :login
  
  def index
    @tweets = Tweet.all.order(created_at: :DESC)
  end
  
  def new 
    @tweet = Tweet.new
  end
  
  def create
    @tweet = @user.tweets.build(message: params[:message])
    if @tweet.save
      redirect_to root_path
    else
      render new_tweet_path
    end
  end

  private
  
  def login
    @user = User.find_by(uid: session[:login_uid]) if session[:login_uid]
    
    redirect_to root_path if @user.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find_by(params[:uid])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(
    uid: params[:user][:uid],
    password: params[:user][:password],
    password_confirmation: params[:user][:password_confirmation])
    if @user.save
      user_log_in @user
      redirect_to root_path
    else
      flash[:danger] = '失敗しました'
      render 'new'
    end
  end

  def edit
    @user = User.find_by(params[:uid])
  end

  def update
    @user = Client.find_by(params[:uid])
    if @user.update(user_params)
      flash[:success] = '更新が完了しました'
      redirect_to root
    else
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find_by(params[:uid])
    if @user.destroy
      redirect_to root
    else
      redirect_to root
    end
  end

  private

  def user_params
    params.require(:user).permit(:uid, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <div>
      <% if session[:login_uid] %>
        <%= "ログイン中のUID: " + session[:login_uid] %>
        <%= button_to 'ログアウト', sessions_logout_path, method: :post %>
      <% end %>
    </div>
  </body>
</html>

app/views/tweets/index.html.erb
<h2> ツイート一覧 </h2>

<% @tweets.each do |tweet| %>
    <div>
        message: <%= tweet.message %>
        uid: <%= tweet.user.uid %>
        <% if Like.where(tweet_id: tweet.id, user_id: @user.id).exists? %>
            <%= link_to 'いいね削除', like_path(tweet.id), method: :delete %>
        <% else %>
            <%= link_to 'いいね', likes_path(tweet_id: tweet.id), method: :post %>
        <% end %>
    </div>
<% end %>

<p> <%= link_to '新規ツイート', new_tweet_path %> </p>
<p> <%= link_to 'ユーザー一覧', users_path %></p>

app/views/tweets/new.html.erb
<%= form_for @tweet, url: { action: :create } do |f| %>
    <%= label_tag :message, 'メッセージ' %>
    <%= text_field_tag :message %>
    <%= submit_tag 'ツイートする' %>
<% end %>

app/views/users/index.html.erb
<h2> ユーザー一覧 </h2>

<% @users.each do |user| %>
    <div>
        <%= user.uid %>
        <%= user.pass %>
    </div>
<% end %>